version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: laravel_php_app
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"  # Port reserved to Laravel.
    working_dir: /var/www/html
    networks:
      - laravel_network
    depends_on:
      - mysql

  vite:
    ports:
      - "5173:5173"

  mysql:
    image: mysql:5.7
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: q8643830
      MYSQL_DATABASE: example_db
      MYSQL_USER: javier
      MYSQL_PASSWORD: abc123
    ports:
      - "3307:3306"  # Map port 3006 inside of my container to 3307 in my local environment.
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: q8643830
    ports:
      - "8081:80"  # Web interface for PhpMyAdmin in the port 8081
    depends_on:
      - mysql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
